import 'dart:convert';

class Welcome {
    String ability;
    String berry;
    String berryFirmness;
    String berryFlavor;
    String characteristic;
    String contestEffect;
    String contestType;
    String eggGroup;
    String encounterCondition;
    String encounterConditionValue;
    String encounterMethod;
    String evolutionChain;
    String evolutionTrigger;
    String gender;
    String generation;
    String growthRate;
    String item;
    String itemAttribute;
    String itemCategory;
    String itemFlingEffect;
    String itemPocket;
    String language;
    String location;
    String locationArea;
    String machine;
    String meta;
    String move;
    String moveAilment;
    String moveBattleStyle;
    String moveCategory;
    String moveDamageClass;
    String moveLearnMethod;
    String moveTarget;
    String nature;
    String palParkArea;
    String pokeathlonStat;
    String pokedex;
    String pokemon;
    String pokemonColor;
    String pokemonForm;
    String pokemonHabitat;
    String pokemonShape;
    String pokemonSpecies;
    String region;
    String stat;
    String superContestEffect;
    String type;
    String version;
    String versionGroup;

    Welcome({
        required this.ability,
        required this.berry,
        required this.berryFirmness,
        required this.berryFlavor,
        required this.characteristic,
        required this.contestEffect,
        required this.contestType,
        required this.eggGroup,
        required this.encounterCondition,
        required this.encounterConditionValue,
        required this.encounterMethod,
        required this.evolutionChain,
        required this.evolutionTrigger,
        required this.gender,
        required this.generation,
        required this.growthRate,
        required this.item,
        required this.itemAttribute,
        required this.itemCategory,
        required this.itemFlingEffect,
        required this.itemPocket,
        required this.language,
        required this.location,
        required this.locationArea,
        required this.machine,
        required this.meta,
        required this.move,
        required this.moveAilment,
        required this.moveBattleStyle,
        required this.moveCategory,
        required this.moveDamageClass,
        required this.moveLearnMethod,
        required this.moveTarget,
        required this.nature,
        required this.palParkArea,
        required this.pokeathlonStat,
        required this.pokedex,
        required this.pokemon,
        required this.pokemonColor,
        required this.pokemonForm,
        required this.pokemonHabitat,
        required this.pokemonShape,
        required this.pokemonSpecies,
        required this.region,
        required this.stat,
        required this.superContestEffect,
        required this.type,
        required this.version,
        required this.versionGroup,
    });}